name: Bug Report
description: Report a reproducible bug or unexpected behavior
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise title of the bug.
      placeholder: e.g., App crashes when clicking on "Login"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps so we can reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: e.g., The login page should load successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: e.g., The app crashed with error code XYZ
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Where did the bug occur?
      placeholder: e.g., iOS 17.0.1, Chrome 126, Ubuntu 22.04
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Attach any relevant logs, stack traces, or screenshots.
      placeholder: Paste error logs here or drag and drop screenshots
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Anything else we should know?
      placeholder: e.g., Happens only when VPN is enabled
    validations:
      required: false
