name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement", "discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        Thanks for taking the time to suggest a feature! Please fill out the details below.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short and clear summary of the feature.
      placeholder: e.g., Add dark mode support
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you need this feature? What problem does it solve?
      placeholder: Explain the need or issue it addresses.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
      placeholder: Describe the solution or approach.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered any alternative solutions or features?
      placeholder: Alternative approaches
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, references, or screenshots here.
      placeholder: Links, images, or examples
    validations:
      required: false
